### ISSUE TITLE
Actions V2 support?

### ISSUE THREAD

**Issue by mwarkentin** [mariamrf/py-package-publish-action#1]
Hi, I was wondering if there are any plans for updates to support the new Actions configurations?

**Comment by webknjaz** [comment]
There's a PyPA project supporting v2: https://github.com/marketplace/actions/pypi-publish.
Guide: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by mariamrf** [comment]
I did not see this..but yeah, I'll work on this maybe sometime this week and close this issue once it's done.
