### ISSUE TITLE
Warning about `pip_version` as input.

### ISSUE THREAD

**Issue by davinchia** [mariamrf/py-package-publish-action#5]
Hi, 

Thanks for the great Github Action! I followed the documentation, configuring `pip_version`, and received the following warning:
```
Warning: Unexpected input(s) 'pip_version', valid inputs are ['entryPoint', 'args', 'python_version', 'subdir']
```

Am I doing something wrong?

Thanks!

**Comment by mariamrf** [comment]
can you share your workflow `.yml` file?

**Comment by davinchia** [comment]
ah yes, I should have done that from the start: https://github.com/davinchia/airbyte/blob/master/.github/workflows/publish-cdk-command.yml#L28

**Comment by mariamrf** [comment]
try using the latest version 1.1.0 this is where this input was introduced (readme seems to be out of date in that regard sorry)

**Comment by davinchia** [comment]
that worked! thank you!
